# Generated by Django 4.2.2 on 2023-06-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enexx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='tipo',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.PROTECT, to='enexx.tipo'),
        ),
    ]
